/**
 * Rules Manager — reads/writes .doctorrc.yml configuration.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { DoctorConfig } from "./types.js";

const DEFAULT_CONFIG: DoctorConfig = {
  files: {
    maxLines: 200,
    criticalLines: 500,
    ignore: [
      "*generated*",
      "*.d.ts",
      "migrations/*.sql",
      "test-data/*.json",
    ],
  },
};

function parseSimpleYaml(content: string): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  let currentSection: Record<string, unknown> | null = null;
  let currentSectionName = "";

  for (const line of content.split("\n")) {
    // Skip comments and blank lines
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    // Section header: "files:"
    if (!line.startsWith(" ") && trimmed.endsWith(":")) {
      currentSectionName = trimmed.slice(0, -1).trim();
      currentSection = {};
      result[currentSectionName] = currentSection;
      continue;
    }

    // Key-value: "  key: value"
    if (line.startsWith("  ") && currentSection) {
      const kvMatch = trimmed.match(/^(\w[\w-]*):\s*(.+)$/);
      if (kvMatch) {
        const key = kvMatch[1];
        let value: unknown = kvMatch[2].trim();

        // Strip inline comment
        const commentIdx = (value as string).indexOf("#");
        if (commentIdx >= 0) {
          value = (value as string).substring(0, commentIdx).trim();
        }

        // Parse numbers
        if (/^\d+$/.test(value as string)) {
          value = parseInt(value as string, 10);
        }
        // Parse booleans
        else if (value === "true") value = true;
        else if (value === "false") value = false;
        // Keep as string (remove quotes if present)
        else if (
          (value as string).startsWith('"') &&
          (value as string).endsWith('"')
        ) {
          value = (value as string).slice(1, -1);
        }

        (currentSection as Record<string, unknown>)[key] = value;
        continue;
      }

      // List item: "  - item"
      const listMatch = trimmed.match(/^-\s+(.+)$/);
      if (listMatch) {
        // Find/make a list key from the last non-list line
        const listKey = Object.keys(currentSection).find(
          (k) => Array.isArray(currentSection![k]),
        );
        if (listKey) {
          (currentSection![listKey] as string[]).push(listMatch[1].trim());
        }
        continue;
      }
    }
  }

  return result;
}

function loadConfig(cwd: string): DoctorConfig {
  const configPath = path.join(cwd, ".doctorrc.yml");

  if (!fs.existsSync(configPath)) {
    return { ...DEFAULT_CONFIG };
  }

  try {
    const content = fs.readFileSync(configPath, "utf-8");
    const parsed = parseSimpleYaml(content);

    return {
      files: {
        maxLines: (parsed.files as any)?.maxLines ?? DEFAULT_CONFIG.files.maxLines,
        criticalLines:
          (parsed.files as any)?.criticalLines ?? DEFAULT_CONFIG.files.criticalLines,
        ignore: Array.isArray((parsed.files as any)?.ignore)
          ? ((parsed.files as any).ignore as string[])
          : DEFAULT_CONFIG.files.ignore,
      },
    };
  } catch {
    return { ...DEFAULT_CONFIG };
  }
}

function saveConfig(cwd: string, config: DoctorConfig): void {
  const configPath = path.join(cwd, ".doctorrc.yml");

  const lines: string[] = [
    "# .doctorrc.yml — generated by context-engineer-doctor",
    "# See /doctor:rules for management",
    "",
    "files:",
    `  maxLines: ${config.files.maxLines}        # warn above this LOC`,
    `  criticalLines: ${config.files.criticalLines}     # error-level above this LOC`,
    "  ignore:",
  ];

  for (const pattern of config.files.ignore || []) {
    lines.push(`    - "${pattern}"`);
  }

  lines.push(""); // trailing newline
  fs.writeFileSync(configPath, lines.join("\n"), "utf-8");
}

export function getConfig(cwd: string): DoctorConfig {
  return loadConfig(cwd);
}

export function initConfig(cwd: string): DoctorConfig {
  const configPath = path.join(cwd, ".doctorrc.yml");

  if (fs.existsSync(configPath)) {
    return loadConfig(cwd);
  }

  const config = { ...DEFAULT_CONFIG };
  saveConfig(cwd, config);
  return config;
}

export function setConfig(
  cwd: string,
  key: string,
  value: string | number,
): { key: string; oldValue: unknown; newValue: unknown } | { error: string } {
  const config = loadConfig(cwd);
  const parts = key.split(".");

  if (parts.length === 2 && parts[0] === "files") {
    const field = parts[1] as keyof DoctorConfig["files"];
    if (field in config.files) {
      const oldValue = config.files[field];
      (config.files as Record<string, unknown>)[field] = value;
      saveConfig(cwd, config);
      return { key, oldValue, newValue: value };
    }
  }

  return { error: `Unknown key: ${key}. Valid keys: files.maxLines, files.criticalLines` };
}
